version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "81:80"
    volumes:
      - ./html:/usr/share/nginx/html
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: my_post_contain
    environment:
      POSTGRES_USER: postgr_me
      POSTGRES_PASSWORD: post123
      POSTGRES_DB: mydatabase
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
